---
title: Product Idea Validation Methods
description: Generate lightweight approaches to test product hypotheses before full development, such as landing pages or limited betas.
tags:
  - strategy
  - metrics
  - creativity
category: Brainstorming
---
Help me brainstorm lightweight ways to validate this product idea before building. I'm looking for scrappy approaches like landing pages, fake door tests, or limited-access betas. [Describe your product idea, your target user, and the assumption you're trying to test.] 